# Generated by Django 3.1.1 on 2020-09-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200920_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='static/empty.png', upload_to='uploads/'),
        ),
    ]
