# Generated by Django 3.1.1 on 2020-09-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200921_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='uploads/empty.png', upload_to='uploads/'),
        ),
    ]
